### ISSUE TITLE
Calendar example does not work without data changes

### ISSUE THREAD

**Issue by likrot** [flotiq/gatsby-starter-event-calendar#18]
Hi,

your `flotiq-cli` is pretty awesome. It is very easy to start a project. But I found one problem with that.

After the project has been created I visited the project's local page and saw that no data was visible. I thought I did something wrong, but I realized, that replicated data contains past dates that do not match the if condition. After fixing everything is ok.

Is there a possibility to dynamically generate event dates so the example works without any changes?

### Issue Summary

No visible data after starting the project.

### To Reproduce

1. Run `flotiq-cli` command `flotiq start [flotiqApiKey] [projectName] https://github.com/flotiq/gatsby-starter-event-calendar`
2. http://localhost:8000/

### Expected behavior

Data should be visible without any changes.

### Technical details:

* Gatsby Version: 2.28.2
* Node Version: 12.20.1
* OS: Windows 10 Pro

**Comment by trzcina** [comment]
Thanks for your suggestion. As you have noticed, events data is not dynamically generated, so events are not always visible in the template (current month, year).

We implemented the possibility to define dynamic dates. Please check out our PR #20 in this repository and the Flotiq-CLI https://github.com/flotiq/flotiq-cli/pull/31. That should solve this problem.

Additionally, we are also preparing new versions of templates (redesigned, compatible with Gatsby v4) - stay tuned :)
